### ISSUE TITLE
Error when removing control using RBNSplitButtonGroupRemoveControl / RBNEndHandler

### ISSUE THREAD

**Issue by ClaireLush** [PeterHorsbollMoller/mbRibbonExample#1]
I have added a SplitButton to a custom tab using the RibbonLib but when the tool is unloaded an error occurs and the control is left in the SplitButton group. The error message is:
![image](https://cloud.githubusercontent.com/assets/11089628/6289839/e19036e8-b91a-11e4-9ace-eeb051168369.png)

**Comment by PeterHorsbollMoller** [comment]
Hi Claire
I had a look at this I the problem might be that you have add a group to your splitbutton before adding the controls. It is however a bit hard to tell as I can't see your code.

I have added an exemple of a new splitbutton tot he RibbonExample here on Github (I'll sync it in just a minute)

The idea is first to create your splitbutton, then add a group to this and finally add controls to this group. I have shortened the code a bit here to better give you an overview. You can see the full example in the RibbonExampleMenu:

nCtrlIdx = RBNGroupAddControl("allInfoToolsSplitButton", ...)
If nCtrlIdx > 0 Then
    Call RBNControlSetIconsIdx(nCtrlIdx, CONTROL_SIZE_LARGE, "", ...)
    nCtrlIdx = RBNSplitButtonAddGroup("allInfoToolsGroup", ..., "allInfoToolsSplitButton")
    If nCtrlIdx > 0 Then
        nCtrlIdx = RBNSplitButtonGroupAddControl("showTablesInfo", ..., "allInfoToolsSplitButton", "allInfoToolsGroup")

**Comment by ClaireLush** [comment]
Hi Peter
I have now been able to have a proper look at this. The issue only occurs where the SplitButton Control being removed is not the last control in the list. It is resolved by exiting the For loop after removing the control:

For nItem = 0 To (nNumCntrls - 1)
    rbnControlItem  = GetMICtrlCollItemInt(rbnControlsColl, nItem)
    If sControlName = GetMICtrlName(rbnControlItem) Then
        Call MICtrlCollRemoveAt(rbnControlsColl, nItem)
        nCtrl = RBNRemoveElement(sTabName, sGroupName, sSplitButtonName, sSplitButtonGroupName, sControlName)
        RBNSplitButtonGroupRemoveControl    = nCtrl
        **Exit For**
    End If
Next

**Comment by PeterHorsbollMoller** [comment]
Ah, have you used the same name to multiple controls on the SplitButton?

That might explain the problem or?

**Comment by ClaireLush** [comment]
Hi Peter

No the button names are different, but the SplitButtonGroup contains multiple controls and the For loop uses the original number of controls to determine the end point of the loop.

Once the control is removed, the collection no longer contains the same number of controls so you get an out of bounds exception when it loops to the last value. Adding the Exit For solves the issue.

Kind regards

Claire Lush
GIS Consultant
exeGesIS Spatial Data Management Ltd

**Comment by PeterHorsbollMoller** [comment]
Ah, thanks.
That surely explains the problem

Peter Horsbøll Møller
GIS/LI Presales Specialist
Location Intelligence | MapInfo

M: +45 29 133 769
peter.moller@pb.commailto:peter.moller@pb.com | @phorsbollmollerhttps://twitter.com/phorsbollmoller
pitneybowes.com/dkhttp://www.pitneybowes.com/dk | mapinfo.comhttp://www.mapinfo.com/

**Comment by PeterHorsbollMoller** [comment]
Hi Claire

Again thanks for pointing out this issue.
In my version of the RibbonLib I have chosen to fix the problem differently. Instead of exiting the sub, I have decided to change the loop order from a forward loop to a backwards loop, that is looping from the largest to the smallest element:

For nItem = (nNumCntrls - 1) To 0 Step -1

In this way the procedure will support removing multiple elements if they have the same name and still it will not fail after removing one element.

I'll upload the new RibbonLib library very soon
